### ISSUE TITLE
could you provide EyelidModel

### ISSUE THREAD

**Issue by ForrestPi** [unclearness/blendshape_line2d_fitting#1]
thanks sharing codes, could you provide EyelidModel and data for test?
I cannot download from the website

**Comment by unclearness** [comment]
Although the link on the website is wrong at this moment, you can download EyelidModel here (changing the root path from university to the personal site).
https://xufeng.site/projects/realtime_3d_eyelids/data/EyelidModel.zip

The author seems to have forgotten to fix the link after their server relocation.

**Comment by ForrestPi** [comment]
https://xufeng.site/projects/realtime_3d_eyelids/data/EyelidModel.zip
http://cgcad.thss.tsinghua.edu.cn/xufeng/realtime_3d_eyelids/data/EyelidModel.zip
http://cgcad.thss.tsinghua.edu.cn/xufeng/realtime_3d_eyelids/data/SemanticEdge.zip

all link cannot be  visited now,   I  have sent a email to the author.
could you send me a copy?

**Comment by unclearness** [comment]
Sorry, my posting was not correct.
http://xufeng.site/projects/realtime_3d_eyelids/data/EyelidModel.zip
Use HTTP! I can access the URL.

I can't put a copy here because re-distribution is not allowed as described on the project page.

**Comment by ForrestPi** [comment]
@unclearness  thanks providing new URL
but how to create  eyelid_model.json, could you provide the related code ?

**Comment by unclearness** [comment]
I fixed `demo.py` to generate `eyelid_model.json`  from authors' objs in `EyelidModel ` directory if it does not exist. Please try the latest commit 3a77bba6e634b36764c9832ccbc7ede07c03ae1f.

**Comment by ForrestPi** [comment]
@unclearness thanks
